[global]
daemonize = no
error_log = /var/log/php-fpm/error.log

[www]
listen = 9000
access.log = /var/log/php-fpm/access.log

; PHP-настройки для этого пула
php_value[post_max_size] = 2G
php_value[upload_max_filesize] = 2G
php_value[max_execution_time] = 3600
php_value[max_input_time] = 3600
php_value[memory_limit] = 512M
php_value[max_file_uploads] = 20
