knpu_oauth2_client:
    clients:
        yandex_main:
            type: yandex
            client_id: '%env(OAUTH_YANDEX_ID)%'
            client_secret: '%env(OAUTH_YANDEX_SECRET)%'
            redirect_route: connect_yandex_check
            redirect_params: {}
