services:
    nginx:
        image: nginx:1.29.8-alpine
        ports:
            - "49020:80"
        volumes:
            - .:/var/www/tech
            - ./docker/nginx/conf:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx
        depends_on:
            php:
                condition: service_started

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            target: dev
        volumes:
            - .:/var/www/tech
            - ./docker/php/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
            - ./docker/php/supervisor/conf:/etc/supervisor/conf.d
            - ~/.gitconfig:/home/appuser/.gitconfig:ro
            - ./docker/php/pool-override.conf:/usr/local/etc/php-fpm.d/zz-override.conf:ro
        dns:
            - 8.8.8.8
            - 1.1.1.1
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        image: mysql:9.7.1
        ports:
            - 49021:3306
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tech
            MYSQL_USER: tech
            MYSQL_PASSWORD: tech
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
            interval: 2s
            timeout: 2s
            retries: 10
            start_period: 15s

    mercure:
        image: dunglas/mercure
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: 'l+GvN1/vT4ik8oxZL848Jm7ehk1zN64oEH0yr8AWBpA='
            MERCURE_SUBSCRIBER_JWT_KEY: 'l+GvN1/vT4ik8oxZL848Jm7ehk1zN64oEH0yr8AWBpA='
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins "*"
                publish_origins "http://localhost:49022"
                anonymous 1
                subscriptions 1
        ports:
            - "49022:80"

    redis:
        image: redis:8.6-alpine3.23
        ports:
            - "49023:6379"
        volumes:
            - ./docker/redis/data:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            timeout: 10s
            retries: 5
            start_period: 5s

volumes:
    mysql_data:
