services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Legacy/'
            - '../src/Domain/Mix/Specification/'
            - '../src/Infrastructure/Mix/Doctrine/Specification/Adapter/'
            - '../src/Domain/User/ValueObject/UserId.php'

    _instanceof:
        App\Application\Message\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Application\Message\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        App\Application\Message\Event\EventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    App\Domain\Mix\Repository\MixRepositoryInterface:
        class: App\Infrastructure\Doctrine\Repository\MixRepository

    App\Infrastructure\Mix\Doctrine\Mapper\MixMapper:
        arguments:
            $userRepository: '@App\Infrastructure\Doctrine\Repository\UserRepository'
