CREATE DATABASE IF NOT EXISTS tech;
CREATE USER IF NOT EXISTS 'tech'@'%' IDENTIFIED BY 'tech';
GRANT ALL PRIVILEGES ON tech.* TO 'tech'@'%';
CREATE DATABASE IF NOT EXISTS tech_test;
GRANT ALL PRIVILEGES ON tech_test.* TO 'tech'@'%';
FLUSH PRIVILEGES;
